name       : qalculate-gtk
version    : 2.2.1
release    : 5
source     :
    - https://github.com/Qalculate/qalculate-gtk/releases/download/v2.2.1/qalculate-gtk-2.2.1.tar.gz : 8bccd336c8b591c33e52d554fdd2c57ca7db6e34420da1e0ad10a15f984f129b
license    : GPL-2.0
component  : office.maths
summary    : Qalculate! is a multi-purpose desktop calculator.
description: |
    Qalculate! is a multi-purpose cross-platform desktop calculator. It is small and simple to use but with much power and versatility underneath. Features include customizable functions, units, arbitrary precision, plotting, and a user-friendly interface.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libqalculate)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
