name       : qalculate-gtk
version    : 2.0.0
release    : 2
source     :
    - https://github.com/Qalculate/qalculate-gtk/releases/download/v2.0.0a/qalculate-gtk-2.0.0.tar.gz : 1fbe6dfedeb7074c795c3c7f01a74867bae27c81325a248f2ae0de8aabd7de2f
license    : GPL-2.0
component  : office.maths
summary    : Qalculate! is a multi-purpose desktop calculator.
description: |
    Qalculate! is a multi-purpose cross-platform desktop calculator. It is small and simple to use but with much power and versatility underneath. Features include customizable functions, units, arbitrary precision, plotting, and a user-friendly interface.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libqalculate)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
