name       : qalculate-gtk
version    : '2.6'
release    : 7
source     :
    - https://github.com/Qalculate/qalculate-gtk/releases/download/v2.6.0/qalculate-gtk-2.6.0.tar.gz : 4918e9c88f5e49c1766fee56cec4468ecad5758d6d2b6637ae5345d159fff55a
license    : GPL-2.0-or-later
component  : office.maths
summary    : Qalculate! is a multi-purpose desktop calculator.
description: |
    Qalculate! is a multi-purpose cross-platform desktop calculator. It is small and simple to use but with much power and versatility underneath. Features include customizable functions, units, arbitrary precision, plotting, and a user-friendly interface.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libqalculate)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
